spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      
    driver-class-name: org.gjt.mm.mysql.Driver        
    url: jdbc:mysql://localhost:3306/smcloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    
